theme: jekyll-theme-slate # whoa how this deviated so much in 2023 hahaha
include: ['_pages', '_redirect']
description: > # this means to ignore newlines until "title:"
  ari's monochrome asylum.
title: arialhamed.github.io
url: ""
markdown: kramdown
timezone: Asia/Singapore
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-redirect-from
  # - jekyll-multiple-languages-plugin
  - jekyll-category-post-navigation
  - jekyll-pdf-embed
  - directory_tag
  - jekyll-remote-include
  - jekyll-last-modified-at
# languages: ["sv", "en", "my", "ch", "id"]
kramdown:
  syntax_highlighter: coderay
# exclude_from_localizations: ["javascript", "css", "static", "LICENSE"]
comment-post: https://docs.google.com/forms/d/e/1FAIpQLSeJJ5CGX171i8bg9T0FnR0ngW-AJ55VkOG4HtICBLsnkUVzkQ
comment-read: https://docs.google.com/spreadsheets/d/15dwbltXqr3tluVzFOAl7tI2ovLmY78QGrTaY8gPDHz8
comment-post-fields: [ entry.1022120595, entry.1922377979, entry.468014524 ]
google_forms_comments:
  comment_replies_enabled: true
  lazy_load_comments: true
collections:
  repos:
    output: true
    permalink: /:collection/:path/
last-modified-at:
  date-format: 'Last modified: %B %d, %y at %H:%M:%S'
